# Generated by Django 4.2.13 on 2026-08-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybook',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
